// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jj-style/gobal-player/cmd/gobal-player-server/internal/biz/globalplayer"
	"github.com/jj-style/gobal-player/cmd/gobal-player-server/internal/config"
	"github.com/jj-style/gobal-player/cmd/gobal-player-server/internal/server"
	"github.com/jj-style/gobal-player/cmd/gobal-player-server/internal/service"
)

// Injectors from wire.go:

func InitializeServer(config2 *config.Config) (*server.Server, func(), error) {
	cache := server.NewCache(config2)
	globalPlayer, cleanup, err := server.NewGlobalPlayer(config2, cache)
	if err != nil {
		return nil, nil, err
	}
	httpClient := globalplayer.NewHttpClient()
	useCase := globalplayer.NewUseCase(globalPlayer, httpClient)
	serviceService := service.NewService(useCase)
	serverServer := server.NewServer(serviceService)
	return serverServer, func() {
		cleanup()
	}, nil
}
