// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: uri
func (_m *MockClient) Get(uri string) ([]byte, error) {
	ret := _m.Called(uri)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(uri)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uri)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - uri string
func (_e *MockClient_Expecter) Get(uri interface{}) *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get", uri)}
}

func (_c *MockClient_Get_Call) Run(run func(uri string)) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(_a0 []byte, _a1 error) *MockClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func(string) ([]byte, error)) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function with given fields: uri, body
func (_m *MockClient) Post(uri string, body interface{}) ([]byte, error) {
	ret := _m.Called(uri, body)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, interface{}) ([]byte, error)); ok {
		return rf(uri, body)
	}
	if rf, ok := ret.Get(0).(func(string, interface{}) []byte); ok {
		r0 = rf(uri, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(uri, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - uri string
//   - body interface{}
func (_e *MockClient_Expecter) Post(uri interface{}, body interface{}) *MockClient_Post_Call {
	return &MockClient_Post_Call{Call: _e.mock.On("Post", uri, body)}
}

func (_c *MockClient_Post_Call) Run(run func(uri string, body interface{})) *MockClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockClient_Post_Call) Return(_a0 []byte, _a1 error) *MockClient_Post_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Post_Call) RunAndReturn(run func(string, interface{}) ([]byte, error)) *MockClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
