name: binaries
on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.pkg }} for ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            pkg: gobal-player-tui
            artifact_name: gobal-player-tui-linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            pkg: gobal-player-server
            artifact_name: gobal-player-server-linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            pkg: gobal-player-server
            artifact_name: gobal-player-server-linux-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@just

      - name: Run tests and publish coverage
        run: just containerize "GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} just build-pkg ${{ matrix.pkg }}"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.artifact_name }}*
          file_glob: true
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
